### ISSUE TITLE
Class reloading issue (rails)

### ISSUE THREAD

**Issue by pietia** [mkristian/dm-hibernate-adapter#15]
```
org.hibernate.MappingException: Unknown entity: org.jruby.RubyObject 
Rails.root: 
app/controllers/users_controller.rb:46:in `create' 
app/controllers/users_controller.rb:45:in `create'
```

Looks like our hooks are not being fired up for :create

**Comment by pietia** [comment]
bigger topic....

**Comment by mkristian** [comment]
the hooks are OK, if you turn off class_caching then things go wrong. basically on startup dm-rails loads all models and somehow rails reloads them and then they are a different ruby class with the same name, i.e. Hibernate.mapped? return true but the second class did not go through become_java!

this can be improved by using the name + the hash of the class, but then you see 
loader (instance of  org/jruby/util/JRubyClassLoader): attempted  duplicate class definition for name: "rubyobj/User"

since the jruby classloader has already a java class. with become_java!(true) the classloading is solved but now Hibernate complains

Duplicate class/entity mapping rubyobj.User

introducing the web classloader we had before jruby-1.6.4 extended become_java! would solve that problem to the extend that hibernate will see only the first class but any changes which effect the hibernate configuration will not be seen. and it could that this web classloader only worked with me (which happens apparently more often)

**Comment by pietia** [comment]
That's exactly what i was thinking about yesterday. Maybe we can re-implement your classloader in jruby?

**Comment by pietia** [comment]
AFAIR torqubox does the same! :)

**Comment by mkristian** [comment]
torquebox does implement a classloader ? I can put the class loader in jruby BUT in java in jruby is pain, everything is manual and you have to be sure to delegate all methods and what about method overloading creating java classes in jruby.

**Comment by pietia** [comment]
i thought torquebox uses custom classloader but after quick chat with Bob, looks like it doesn't. They use become_java!(false)

**Comment by pietia** [comment]
Closing, we will reopen if needed.
